<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class tabel_mst_employee extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('sys_table')->where(['gmenu' => 'master', 'dmenu' => 'msempl'])->delete();

        DB::table('sys_table')->insert(
            [
                'gmenu' => "master",
                'dmenu' => "msempl",
                'urut' => "1",
                'field' => "empl_username",
                'alias' => "Username",
                'type' => "string",
                'length' => "20",
                'decimals' => "0",
                'default' => "",
                'validate' => "required|max:255|min:2|unique:users,username",
                'primary' => "1",
                'generateid' => "",
                'filter' => "1",
                'list' => "1",
                'show' => "1",
                'query' => "",
                'class' => "lower notspace",
                'sub' => "",
                'link' => "",
                'note' => "",
                'position' => "0",
                'isactive' => "1",
                'created_at' => "2025-07-23 13:55:28",
                'updated_at' => "2025-07-23 13:55:28",
                'user_create' => "",
                'user_update' => "",
            ]
        );
        DB::table('sys_table')->insert(
            [
                'gmenu' => "master",
                'dmenu' => "msempl",
                'urut' => "2",
                'field' => "empl_firstname",
                'alias' => "First Name",
                'type' => "string",
                'length' => "255",
                'decimals' => "0",
                'default' => "",
                'validate' => "required|max:255|min:2",
                'primary' => "0",
                'generateid' => "",
                'filter' => "1",
                'list' => "1",
                'show' => "1",
                'query' => "",
                'class' => "upper",
                'sub' => "",
                'link' => "",
                'note' => "",
                'position' => "0",
                'isactive' => "1",
                'created_at' => "2025-07-23 13:55:28",
                'updated_at' => "2025-07-23 13:55:28",
                'user_create' => "",
                'user_update' => "",
            ]
        );
        DB::table('sys_table')->insert(
            [
                'gmenu' => "master",
                'dmenu' => "msempl",
                'urut' => "3",
                'field' => "empl_lastname",
                'alias' => "Last Name",
                'type' => "string",
                'length' => "255",
                'decimals' => "0",
                'default' => "",
                'validate' => "required|max:255|min:2",
                'primary' => "0",
                'generateid' => "",
                'filter' => "1",
                'list' => "1",
                'show' => "1",
                'query' => "",
                'class' => "",
                'sub' => "",
                'link' => "",
                'note' => "",
                'position' => "0",
                'isactive' => "1",
                'created_at' => "2025-07-23 13:55:28",
                'updated_at' => "2025-07-23 13:55:28",
                'user_create' => "",
                'user_update' => "",
            ]
        );
        DB::table('sys_table')->insert([
            'gmenu' => 'master',
            'dmenu' => 'msempl',
            'urut' => '4',
            'field' => 'empl_email',
            'alias' => 'Email',
            'type' => 'email',
            'length' => '255',
            'decimals' => '0',
            'default' => '',
            'validate' => 'required|email|max:255|unique:mst_employee,empl_email', // Ubah dari users ke mst_employee
            'primary' => '0',
            'generateid' => '',
            'filter' => '1',
            'list' => '1',
            'show' => '1',
            'query' => '',
            'class' => '',
            'sub' => '',
            'link' => '',
            'note' => '',
            'position' => '0',
            'isactive' => '1',
            'created_at' => '2025-07-23 13:55:28',
            'updated_at' => '2025-07-23 13:55:28',
            'user_create' => '',
            'user_update' => '',
        ]);
        DB::table('sys_table')->insert(
            [
                'gmenu' => "master",
                'dmenu' => "msempl",
                'urut' => "5",
                'field' => "empl_idroles",
                'alias' => "ID Roles",
                'type' => "enum",
                'length' => "6",
                'decimals' => "0",
                'default' => "",
                'validate' => "required",
                'primary' => "0",
                'generateid' => "",
                'filter' => "1",
                'list' => "1",
                'show' => "1",
                'query' => "select idroles, name from sys_roles where isactive = '1'",
                'class' => "select-multiple custom-select",
                'sub' => "",
                'link' => "",
                'note' => "",
                'position' => "0",
                'isactive' => "1",
                'created_at' => "2025-07-23 13:55:28",
                'updated_at' => "2025-07-23 13:55:28",
                'user_create' => "",
                'user_update' => "",
            ]
        );
        DB::table('sys_table')->insert(
            [
                'gmenu' => "master",
                'dmenu' => "msempl",
                'urut' => "7",
                'field' => "empl_password",
                'alias' => "Password",
                'type' => "password",
                'length' => "50",
                'decimals' => "0",
                'default' => "MSJframework123!",
                'validate' => "required|max:50|min:6|regex:/^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[\W_]).+$/",
                'primary' => "0",
                'generateid' => "",
                'filter' => "1",
                'list' => "0",
                'show' => "1",
                'query' => "",
                'class' => "",
                'sub' => "",
                'link' => "",
                'note' => "",
                'position' => "0",
                'isactive' => "1",
                'created_at' => "2025-07-23 13:55:28",
                'updated_at' => "2025-07-23 13:55:28",
                'user_create' => "",
                'user_update' => "",
            ]
        );
        DB::table('sys_table')->insert(
            [
                'gmenu' => "master",
                'dmenu' => "msempl",
                'urut' => "8",
                'field' => "isactive",
                'alias' => "Status",
                'type' => "enum",
                'length' => "1",
                'decimals' => "0",
                'default' => "1",
                'validate' => "",
                'primary' => "0",
                'generateid' => "",
                'filter' => "1",
                'list' => "1",
                'show' => "0",
                'query' => "select value, name from sys_enum where idenum = 'isactive' and isactive = '1'",
                'class' => "",
                'sub' => "",
                'link' => "",
                'note' => "",
                'position' => "0",
                'isactive' => "1",
                'created_at' => "2025-07-23 13:55:28",
                'updated_at' => "2025-07-23 13:55:28",
                'user_create' => "",
                'user_update' => "",
            ]
        );
        DB::table('sys_table')->insert(
            [
                'gmenu' => "master",
                'dmenu' => "msempl",
                'urut' => "9",
                'field' => "empl_image",
                'alias' => "Foto Profil",
                'type' => "image",
                'length' => "2048",
                'decimals' => "0",
                'default' => "noimage.png",
                'validate' => "mimes:png,PNG,jpg,JPG,jpeg,JPEG|file|max:2048",
                'primary' => "0",
                'generateid' => "",
                'filter' => "1",
                'list' => "1",
                'show' => "1",
                'query' => "",
                'class' => "",
                'sub' => "",
                'link' => "",
                'note' => "",
                'position' => "0",
                'isactive' => "1",
                'created_at' => "2025-07-23 13:55:28",
                'updated_at' => "2025-07-23 13:55:28",
                'user_create' => "",
                'user_update' => "",
            ]
        );
    }
}
